### ISSUE TITLE
Example III only prints a html like text to stdout

### ISSUE THREAD

**Issue by sbthandras** [phageaisa/phageai#5] opened 2022-09-15 11:28 UTC
Hey I ran into a problem when I was trying to retrieve records of phages by accession numbers.

The reproduction of the problem is 

pip install phageai
creating a .py script by pasting example III and of course my accession token correctly

then running the script as
python3 script.py 

returns a html-llike text instead of the record

the text is here: https://justpaste.it/8plev

I checked and I have correct versions of all the requirements and python

Thanks in advance!

**Comment by krzysieqq** [comment] 2022-09-15 13:30
Hi @sbthandras,
Can you paste content of your `script.py` of course without your access token, or if it not possible can you give us information about what value your're passing to `get_record` or `get_top10_similar_phages`?

**Comment by sbthandras** [comment] 2022-09-15 14:10
yes: 

from phageai.repository.phages import BacteriophageRepository

phageai_repo = BacteriophageRepository(access_token='acces-token')

# Get bacteriophage meta-data based on accession number (or hash value)
# It can return one or more than one results
phageai_repo.get_record(value='MZ375324')


# Get top 10 similar bacteriophage samples
phageai_repo.get_top10_similar_phages(value='MZ375324')

**Comment by ptynecki** [comment] 2022-09-15 15:18
@sbthandras Can you paste the phageai package version which you have in your env?

Feel free to use:

```bash
pip list | grep phageai
```

**Comment by sbthandras** [comment] 2022-09-15 15:25
phageai             0.3.1

**Comment by ptynecki** [comment] 2022-09-15 15:35
@sbthandras 

Got it. You have to upgrade the package to the newest stable version.

```bash
pip3 install phageai --upgrade --force-reinstall --no-cache-dir
```

After that, try the script execution again.

**Comment by sbthandras** [comment] 2022-09-16 07:51
Hey!


Thanks this got the line executed successfully however now it returns an empty list

**Comment by ptynecki** [comment] 2022-09-16 12:23
@sbthandras 

I can confirm that for `MZ375324` the list is empty. It is because that phage is not anymore in our repository. PhageAI shares only high quality phage after the v1.0 platform upgrade (released in August 2022). `MZ375324` sample does not pass those criteria.

We will update the README.md with another phage example this week.

**Comment by sbthandras** [comment] 2022-09-16 12:28
Indeed now it works in all of the cases where you have the phage in your database.
Thank you very much for the quick and helpful response to my ticket!

**Closed** 2022-09-29 11:36 UTC
